### PR TITLE
Standalone utility for generating metadata

### PR DESCRIPTION
**Pull request by sethfitz**
Generates OIN-compliant metadata on stdout from a local file.

Refs #2

### CODE REVIEW

**Comment by smit1678** [comment]
@mojodna 👍 awesome. Does this happen to address https://github.com/hotosm/oam-uploader-api/issues/42?

**Comment by sethfitz** [comment]
Nope. I did isolate the problematic line though: https://github.com/openimagerynetwork/oin-meta-generator/blob/master/lib/apply-gdalinfo.js#L12

**Comment by smit1678** [comment]
@mojodna Can you knock out a quick README update here for usage as well? We can always come back with a more detailed README update.

**Comment by sethfitz** [comment]
Surely.

**Comment by sethfitz** [comment]
README updated, minor nits encountered in the process fixed.

**Pull request merged**
